import React from 'react';
import PolicyDocument, { type PolicyCopy } from '@/components/PolicyDocument';
import { getLanguageFromHeaders, type UiLanguage } from '@/lib/server-utils';

const TERMS_TEXT: Record<UiLanguage, PolicyCopy> = {
  ko: {
    title: "이용약관",
    updated: "최종 수정일: 2026년 9월 13일",
    intro:
      "Transfy는 스포티파이에서 재생 중인 곡의 가사를 가져와 실시간으로 번역해 보여 주는 서비스입니다. 개인이 학습을 목적으로 만들어 무료로 운영하는 비상업적 프로젝트이며, 이 서비스를 이용하시면 아래 내용에 동의하신 것으로 봅니다.",
    sections: [
      {
        title: "1. 이용 범위",
        body: "개인적인 감상을 목적으로 누구나 무료로 이용하실 수 있습니다. 다만 다음 행위는 삼가 주시기 바랍니다.",
        list: [
          "자동화된 수단으로 대량의 요청을 보내 서비스 운영을 방해하는 행위",
          "이 서비스가 보여 주는 가사와 번역을 상업적인 목적으로 재배포하는 행위",
          "이 서비스나 연동된 외부 서비스가 정상적으로 동작하지 못하도록 우회하거나 방해하는 행위",
        ],
      },
      {
        title: "2. 가사와 저작권",
        body: "가사 원문은 LRCLIB에서 제공받으며, 가사와 음원에 관한 모든 권리는 원저작자와 권리자에게 있습니다. Transfy는 가사를 직접 보유하거나 판매하지 않고, 이용자가 듣고 있는 곡에 맞추어 보여 줄 뿐입니다. 권리자께서 특정 곡의 게시 중단을 요청하시면 확인한 뒤에 조치하겠습니다.",
      },
      {
        title: "3. 번역 결과의 정확도",
        body: "번역문은 기계 번역으로 자동 생성되기 때문에 원문의 뜻과 다르게 옮겨질 수 있습니다. 특히 관용 표현이나 비유가 많은 가사는 정확도가 떨어집니다. 번역문을 학습이나 인용의 근거로 삼으실 때에는 반드시 원문을 함께 확인해 주세요.",
      },
      {
        title: "4. 외부 서비스와의 관계",
        body: "Transfy는 Spotify AB, Apple Inc., LRCLIB를 비롯한 어떤 외부 서비스와도 제휴하거나 후원을 받는 관계가 아닙니다. 각 서비스의 이름과 상표는 해당 권리자의 것이며, 스포티파이 계정으로 로그인하는 기능은 스포티파이가 공개한 API를 통해 제공됩니다.",
      },
      {
        title: "5. 서비스의 변경과 중단",
        body: "개인이 운영하는 프로젝트이므로 서비스의 내용이 바뀌거나, 미리 알려 드리지 못한 채 일시적으로 또는 영구히 중단될 수 있습니다. 연동된 외부 서비스의 정책이 바뀌거나 장애가 생기면 가사 조회와 번역이 동작하지 않을 수도 있습니다.",
      },
      {
        title: "6. 책임의 한계",
        body: "Transfy는 있는 그대로 제공되며, 특정한 목적에 들어맞는다거나 오류가 없다는 점을 보증하지 않습니다. 법이 허용하는 범위에서, 이 서비스를 이용하는 과정에서 생긴 손해에 대해서는 책임을 지지 않습니다.",
      },
      {
        title: "7. 약관의 변경",
        body: "약관이 바뀌면 바뀐 내용과 최종 수정일을 이 화면에 함께 반영합니다. 변경된 뒤에도 서비스를 계속 이용하시면 바뀐 약관에 동의하신 것으로 봅니다.",
      },
    ],
    contactTitle: "8. 문의와 오류 제보",
    contactDesc:
      "서비스를 이용하시다가 가사가 어긋나거나 번역이 이상하게 나오는 등 잘못된 점을 발견하셨다면, 아래 주소로 알려 주세요. 어떤 곡에서 어떤 문제가 있었는지 함께 적어 주시면 확인한 뒤에 고치겠습니다. 게시 중단 요청도 같은 주소로 보내 주시면 됩니다.",
    back: "← 홈으로 돌아가기",
  },
  en: {
    title: "Terms of Service",
    updated: "Last updated: September 13, 2026",
    intro:
      "Transfy shows the lyrics of the song you are playing on Spotify and translates them as it plays. It is a free, non-commercial project built and run by one person for learning purposes. By using the service, you agree to the terms below.",
    sections: [
      {
        title: "1. How You May Use Transfy",
        body: "Anyone may use Transfy free of charge for personal listening. Please do not do any of the following:",
        list: [
          "Send bulk automated requests that interfere with the running of the service.",
          "Redistribute the lyrics or translations shown here for commercial purposes.",
          "Bypass or disrupt how this service, or the external services it relies on, are meant to work.",
        ],
      },
      {
        title: "2. Lyrics and Copyright",
        body: "Lyrics come from LRCLIB, and all rights to the lyrics and the recordings belong to their authors and rights holders. Transfy neither owns nor sells lyrics; it only displays them alongside the song you are listening to. If you hold the rights to a song and would like it taken down, tell us and we will act on it once we have checked.",
      },
      {
        title: "3. Accuracy of Translations",
        body: "Translations are generated by machine translation, so they can differ from what the original lines mean. Lyrics rich in idioms or figurative language suffer the most. Always read the original lines alongside the translation before relying on it for study or quotation.",
      },
      {
        title: "4. Relationship with Other Services",
        body: "Transfy is not affiliated with, endorsed by, or sponsored by Spotify AB, Apple Inc., LRCLIB, or any other service. All names and trademarks belong to their respective owners, and signing in with Spotify works through the API that Spotify publishes.",
      },
      {
        title: "5. Changes and Interruptions",
        body: "Because one person runs this project, the service may change, or be suspended or shut down without advance notice. Lyrics and translation may also stop working when the external services it depends on change their policies or go down.",
      },
      {
        title: "6. Disclaimer",
        body: "Transfy is provided on an 'as is' basis, with no warranty that it fits a particular purpose or is free of errors. To the extent the law allows, we are not liable for damage arising from your use of the service.",
      },
      {
        title: "7. Changes to These Terms",
        body: "When these terms change, the new text and the date above are updated on this page. If you keep using the service after a change, you accept the updated terms.",
      },
    ],
    contactTitle: "8. Contact and Bug Reports",
    contactDesc:
      "If you notice anything wrong while using Transfy, such as mismatched lyrics or a strange translation, please let us know at the address below. Telling us which track was affected and what went wrong helps us look into it and fix it. Takedown requests go to the same address.",
    back: "← Back to Home",
  },
  ja: {
    title: "利用規約",
    updated: "最終更新日: 2026年9月13日",
    intro:
      "Transfyは、Spotifyで再生中の曲の歌詞を取得し、リアルタイムで翻訳して表示するサービスです。個人が学習を目的として制作し、無料で運営している非営利プロジェクトであり、本サービスをご利用いただいた時点で以下の内容に同意したものとみなします。",
    sections: [
      {
        title: "1. ご利用の範囲",
        body: "個人的な鑑賞を目的として、どなたでも無料でご利用いただけます。ただし、次の行為はお控えください。",
        list: [
          "自動化された手段で大量のリクエストを送信し、サービスの運営を妨げる行為",
          "本サービスが表示する歌詞や翻訳を商業目的で再配布する行為",
          "本サービスや連携する外部サービスが正常に動作しないよう迂回し、または妨害する行為",
        ],
      },
      {
        title: "2. 歌詞と著作権",
        body: "歌詞の原文はLRCLIBから提供を受けており、歌詞と音源に関するすべての権利は原著作者および権利者に帰属します。Transfyは歌詞を自ら保有したり販売したりすることはなく、利用者が聴いている曲に合わせて表示するだけです。権利者の方から特定の曲の掲載停止をご要望いただいた場合は、確認のうえ対応いたします。",
      },
      {
        title: "3. 翻訳の正確さ",
        body: "翻訳文は機械翻訳によって自動生成されるため、原文の意味と異なって訳される場合があります。特に慣用表現や比喩の多い歌詞では正確さが落ちます。翻訳文を学習や引用の根拠とされる際は、必ず原文もあわせてご確認ください。",
      },
      {
        title: "4. 外部サービスとの関係",
        body: "Transfyは、Spotify AB、Apple Inc.、LRCLIBをはじめとするいかなる外部サービスとも提携しておらず、後援も受けていません。各サービスの名称および商標はそれぞれの権利者に帰属し、Spotifyアカウントでのログイン機能はSpotifyが公開しているAPIを通じて提供されています。",
      },
      {
        title: "5. サービスの変更と停止",
        body: "個人が運営するプロジェクトのため、サービスの内容が変更されたり、事前のお知らせなく一時的または恒久的に停止したりする場合があります。連携する外部サービスの方針変更や障害により、歌詞の取得と翻訳が動作しないこともあります。",
      },
      {
        title: "6. 免責事項",
        body: "Transfyは現状のまま提供され、特定の目的に適合すること、または誤りがないことを保証するものではありません。法律が認める範囲において、本サービスのご利用によって生じた損害について責任を負いません。",
      },
      {
        title: "7. 規約の変更",
        body: "規約を変更した場合は、変更後の内容と最終更新日をこの画面に反映します。変更後も引き続きご利用いただいた場合は、変更後の規約に同意したものとみなします。",
      },
    ],
    contactTitle: "8. お問い合わせと不具合のご報告",
    contactDesc:
      "ご利用中に歌詞がずれている、翻訳がおかしいなど、誤りにお気づきの際は下記の宛先までお知らせください。どの曲でどのような問題が起きたかを添えていただけますと、確認のうえ修正いたします。掲載停止のご要望も同じ宛先で承ります。",
    back: "← ホームに戻る",
  },
  zh: {
    title: "服务条款",
    updated: "最后更新日期：2026年9月13日",
    intro:
      "Transfy 会获取您在 Spotify 上正在播放的歌曲歌词，并实时翻译后显示。这是个人出于学习目的制作、免费运营的非商业项目，您使用本服务即视为同意以下内容。",
    sections: [
      {
        title: "1. 使用范围",
        body: "任何人都可以出于个人欣赏的目的免费使用。但请不要进行以下行为：",
        list: [
          "通过自动化手段发送大量请求，妨碍服务的运行",
          "将本服务显示的歌词和译文用于商业目的再分发",
          "绕过或妨碍本服务及其所连接的外部服务的正常运行",
        ],
      },
      {
        title: "2. 歌词与著作权",
        body: "歌词原文由 LRCLIB 提供，歌词和录音的一切权利归原作者及权利人所有。Transfy 既不持有也不出售歌词，只是配合您正在收听的歌曲将其显示出来。如果权利人要求下架某首歌曲，我们会在核实后处理。",
      },
      {
        title: "3. 译文的准确性",
        body: "译文由机器翻译自动生成，可能与原文的意思有出入，惯用语和比喻较多的歌词尤其如此。将译文用作学习或引用依据时，请务必同时对照原文。",
      },
      {
        title: "4. 与外部服务的关系",
        body: "Transfy 与 Spotify AB、Apple Inc.、LRCLIB 等任何外部服务均无合作或赞助关系。各服务的名称与商标归各自权利人所有，使用 Spotify 账户登录的功能通过 Spotify 公开的 API 提供。",
      },
      {
        title: "5. 服务的变更与中断",
        body: "本项目由个人运营，服务内容可能发生变更，也可能在未事先通知的情况下暂时或永久停止。所连接的外部服务调整政策或发生故障时，歌词获取与翻译也可能无法运行。",
      },
      {
        title: "6. 免责声明",
        body: "Transfy 按现状提供，不保证适合特定用途，也不保证没有错误。在法律允许的范围内，我们不对您使用本服务过程中产生的损害承担责任。",
      },
      {
        title: "7. 条款的变更",
        body: "条款变更时，我们会将变更后的内容和最后更新日期一并反映在本页面。变更后继续使用本服务，即视为您同意变更后的条款。",
      },
    ],
    contactTitle: "8. 联系与问题反馈",
    contactDesc:
      "使用过程中如果发现歌词不同步、翻译异常等问题，请通过下面的邮箱告诉我们。附上是哪首歌、出现了什么问题，我们会核实后修正。下架请求也请发送到同一邮箱。",
    back: "← 返回首页",
  },
};

export default async function TermsPage() {
  const lang = await getLanguageFromHeaders();

  return <PolicyDocument copy={TERMS_TEXT[lang]} />;
}
